name:                 epic
version:              0.1.0.0
synopsis:             A simple purely functional embedded language
homepage:             https://github.com/thoferon/epic#readme
license:              BSD3
author:               Thomas Feron
maintainer:           thomas.feron@redspline.com
copyright:            2017 Thomas Feron
category:             Language

extra-source-files:
  - README.md

ghc-options:          -Wall

dependencies:
  - attoparsec
  - base >= 4.7 && < 5
  - lens
  - mtl
  - recursion-schemes
  - text

default-extensions:
  - DefaultSignatures
  - DeriveFunctor
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - PatternSynonyms
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeOperators

library:
  source-dirs:        src
  dependencies:
    - deriving-compat
    - directory
    - filepath
    - template-haskell

tests:
  unit-tests:
    source-dirs:      tests
    main:             Main.hs
    dependencies:
      - epic
      - hedgehog
      - tasty
      - tasty-hedgehog
      - tasty-hunit
